apt update && apt upgrade
apt install git 
apt install python
apt install python2
apt install php
apt install openssh
pip install termcolor
pip install b0mb3r
pkg install wget
pkg install php
pkg install python
pkg install python2
pip install vk
pip install vk_api
pip install bs4
pip install pysocks
pip install prettytable
git clone https://github.com/termux-lab/smsham.git 
git clone https://github.com/4D4N-Termux/hambom.git
git clone https://github.com/termux-lab/kingfish.git
git clone https://github.com/termux-lab/kingfish2.0.git
git clone https://github.com/termux-lab/kingfish3.git
git clone https://github.com/htr-tech/nexphisher.git
git clone https://github.com/AnonHackerr/toolss.git
git clone https://github.com/4D4N-Termux/aiohttpdos.git
